(()=>{'use strict';
const audio=document.querySelector('#bgm'),music=document.querySelector('.music-control'),enter=document.querySelector('#enter');let userPaused=false;
audio.volume=.5;
function preventCoverScroll(event){if(!document.body.classList.contains('entered'))event.preventDefault()}
document.addEventListener('touchmove',preventCoverScroll,{passive:false});document.addEventListener('wheel',preventCoverScroll,{passive:false});document.addEventListener('keydown',event=>{if(!document.body.classList.contains('entered')&&['ArrowDown','ArrowUp','PageDown','PageUp','Home','End',' '].includes(event.key)&&!event.target.closest('button,a,input,textarea,select'))event.preventDefault()});
if(!document.body.classList.contains('entered'))window.scrollTo(0,0);
function toast(message){const el=document.querySelector('.toast');el.textContent=message;el.classList.add('show');clearTimeout(toast.timer);toast.timer=setTimeout(()=>el.classList.remove('show'),3000)}
let musicState='idle',playPending=false,wantsMusic=false;
const musicSource=audio.canPlayType('audio/mp4; codecs="mp4a.40.2"')?'https://wedding-music-1501189482.cos.ap-nanjing.myqcloud.com/10000-hours.m4a':'https://wedding-music-1501189482.cos.ap-nanjing.myqcloud.com/10000-hours.mp3';
audio.preload='auto';audio.src=musicSource;audio.muted=false;audio.volume=1;audio.load();
function syncMusic(){const playing=musicState==='playing'&&!audio.paused;music.classList.toggle('playing',playing);music.setAttribute('aria-pressed',String(playing));music.setAttribute('aria-label',playing?'暂停背景音乐':'播放背景音乐');music.querySelector('span').textContent=playing?'暂停':musicState==='loading'?'加载中':'音乐'}
function playMusic(notify=false){wantsMusic=true;if(userPaused||playPending)return;playPending=true;musicState='loading';syncMusic();let result;try{result=audio.play()}catch(error){failed(error);return}Promise.resolve(result).then(()=>{playPending=false;musicState='playing';syncMusic()}).catch(failed);function failed(error){playPending=false;musicState='idle';syncMusic();if(notify)toast(error.name==='NotAllowedError'?'请轻触右上角音乐按钮开始播放':'音乐暂未播放，请轻触右上角重试')}}
audio.addEventListener('playing',()=>{musicState='playing';syncMusic()});audio.addEventListener('waiting',()=>{musicState='loading';syncMusic()});audio.addEventListener('pause',()=>{musicState='idle';syncMusic()});
audio.addEventListener('canplay',()=>{if(wantsMusic&&!userPaused&&audio.paused)playMusic()});
audio.addEventListener('error',()=>{playPending=false;musicState='idle';syncMusic();if(!audio.src.includes('10000-hours.mp3')){audio.src='https://wedding-music-1501189482.cos.ap-nanjing.myqcloud.com/10000-hours.mp3';audio.load();if(wantsMusic&&!userPaused)playMusic(true)}else toast('音乐加载失败，请轻触音乐按钮重试')});
music.addEventListener('click',()=>{if(wantsMusic&&!audio.paused){userPaused=true;wantsMusic=false;audio.pause()}else{userPaused=false;if(audio.error){audio.load();playPending=false}playMusic(true)}});
// Invoke playback directly in the mobile gesture before the entrance animation.
enter.addEventListener('touchend',()=>{userPaused=false;playMusic(true)},{passive:true});
document.addEventListener('WeixinJSBridgeReady',()=>{if(wantsMusic&&!userPaused)playMusic()});
document.addEventListener('visibilitychange',()=>{if(!document.hidden&&wantsMusic&&!userPaused&&audio.paused)playMusic()});
const states=new WeakMap();
function loadPhoto(shell){if(states.get(shell)==='loading'||states.get(shell)==='loaded')return;states.set(shell,'loading');shell.classList.remove('load-error');shell.classList.add('pending');shell.setAttribute('aria-busy','true');shell.querySelector('.load-label').textContent='照片载入中';const img=shell.querySelector('img'),source=shell.querySelector('source');
 const done=()=>{states.set(shell,'loaded');shell.classList.remove('pending','load-error');shell.classList.add('loaded');shell.setAttribute('aria-busy','false')};
 const failed=()=>{states.set(shell,'error');shell.classList.remove('pending');shell.classList.add('load-error');shell.setAttribute('aria-busy','false');shell.querySelector('.load-label').textContent='加载失败，轻触重试'};
 img.onload=done;img.onerror=failed;if(source.dataset.srcset){source.srcset=source.dataset.srcset;delete source.dataset.srcset}if(img.dataset.src){img.src=img.dataset.src;delete img.dataset.src}else{const retry='?retry='+Date.now();source.srcset='https://wedding-music-1501189482.cos.ap-nanjing.myqcloud.com/'+shell.dataset.photo+'.webp'+retry;img.src='https://wedding-music-1501189482.cos.ap-nanjing.myqcloud.com/'+shell.dataset.photo+'.jpg'+retry}if(img.complete&&img.naturalWidth>0)done();
}
const modules=[...document.querySelectorAll('[data-module]')];let moduleObserver,revealObserver;
function activate(module){module.querySelectorAll('.photo-shell').forEach(loadPhoto)}
if('IntersectionObserver' in window){moduleObserver=new IntersectionObserver(entries=>entries.forEach(e=>{if(e.isIntersecting){activate(e.target);moduleObserver.unobserve(e.target)}}),{rootMargin:'180px 0px',threshold:0});revealObserver=new IntersectionObserver(entries=>entries.forEach(e=>{if(e.isIntersecting){e.target.classList.add('in-view');revealObserver.unobserve(e.target)}}),{threshold:.08});}
function startChapters(){modules.forEach(module=>{if(moduleObserver){moduleObserver.observe(module);revealObserver.observe(module)}else{activate(module);module.classList.add('in-view')}})}
enter.addEventListener('click',()=>{userPaused=false;playMusic(true);if(!document.body.classList.contains('entered')){document.body.classList.add('entered');enter.textContent='继续浏览我们的请柬 ↓';startChapters()}requestAnimationFrame(()=>document.querySelector('#invitation').scrollIntoView({behavior:matchMedia('(prefers-reduced-motion: reduce)').matches?'auto':'smooth'}))});
const box=document.querySelector('#lightbox'),full=document.querySelector('#full-image'),fullState=document.querySelector('.full-image-state');document.querySelectorAll('.photo-shell').forEach(shell=>shell.addEventListener('click',()=>{if(states.get(shell)==='error'){loadPhoto(shell);return}fullState.textContent='原片加载中…';full.alt=shell.querySelector('img').alt;full.onload=()=>{fullState.textContent=''};full.onerror=()=>{fullState.textContent='原片加载失败，请关闭后重试'};full.src='https://wedding-music-1501189482.cos.ap-nanjing.myqcloud.com/'+shell.dataset.photo+'-original.jpg';box.showModal()}));document.querySelector('#close-photo').addEventListener('click',()=>box.close());box.addEventListener('click',e=>{if(e.target===box)box.close()});
const address='君心喜悦彭城盛宴宴会酒店 · 鎏金岁月厅\n泉山区湖北路与纺织东路交叉口南40米';document.querySelector('#copy-address').addEventListener('click',async()=>{try{await navigator.clipboard.writeText(address);toast('婚宴地址已复制')}catch{const field=document.createElement('textarea');field.value=address;field.style.position='fixed';field.style.opacity='0';document.body.append(field);field.select();const ok=document.execCommand('copy');field.remove();toast(ok?'婚宴地址已复制':'请长按页面上的地址复制')}});
const days=Math.ceil((new Date('2026-10-25T11:38:00+08:00')-Date.now())/86400000);document.querySelector('#countdown').textContent=days>0?'距离我们的婚礼，还有 '+days+' 天':'赴一场幸福之约 · 2026.10.25';
let scheduled=false;window.addEventListener('scroll',()=>{if(scheduled)return;scheduled=true;requestAnimationFrame(()=>{const max=document.documentElement.scrollHeight-innerHeight;document.querySelector('.scroll-progress').style.transform='scaleX('+(max>0?Math.min(1,Math.max(0,scrollY/max)):0)+')';scheduled=false})},{passive:true});
})();
